version: 0.0
os: linux
files:
  - source: scripts/simple.yml
    destination: /home/ec2-user/simple.yml
hooks:
  BeforeInstall:
    - location: scripts/runansible.sh
      timeout: 60
      runas: root
